## Aplicação das Features
Transformando dados brutos em variáveis úteis para o modelo

In [ ]:
# Importação de bibliotecas
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd
from src.features.clean_text import limpeza_texto

# Definição do caminho do dataset
dataset_csv_path = '../data/dataset.csv'

# Carregamento do dataset
df = pd.read_csv(dataset_csv_path)

In [2]:
# Aplicando função de limpeza 'limpeza_texto'
df['texto_limpo'] = df['texto_review'].apply(limpeza_texto)

print("Resultado após realização da limpeza de texto: ")
df.head()

Resultado após realização da limpeza de texto:

,review_id,texto_review,sentimento,texto_limpo
0,1,Estou muito feliz com a compra. O cadeira game...,positivo,estou muito feliz com a compra o cadeira gamer...
1,2,NaN,negativo,
2,3,Não recomendo. A entrega foi lenta e o celular...,negativo,nao recomendo a entrega foi lenta e o celular ...
3,4,O monitor é decepcionante. O suporte ao client...,positivo,o monitor e decepcionante o suporte ao cliente...
4,5,É UM LIVRO OK PELO PRÇEO QUE PAGUEI.,negativo,e um livro ok pelo prceo que paguei

In [3]:
# Mapeamento para transformar dados de 'sentimento' em valores números 0 e 1
df['sentimento_value'] = df['sentimento'].map({'positivo': 1, 'negativo': 0})
df.head()

,review_id,texto_review,sentimento,texto_limpo,sentimento_value
0,1,Estou muito feliz com a compra. O cadeira game...,positivo,estou muito feliz com a compra o cadeira gamer...,1
1,2,NaN,negativo,,0
2,3,Não recomendo. A entrega foi lenta e o celular...,negativo,nao recomendo a entrega foi lenta e o celular ...,0
3,4,O monitor é decepcionante. O suporte ao client...,positivo,o monitor e decepcionante o suporte ao cliente...,1
4,5,É UM LIVRO OK PELO PRÇEO QUE PAGUEI.,negativo,e um livro ok pelo prceo que paguei,0

In [5]:
print("DataFrame limpo após limpeza e mapeamento:\n")
df[['texto_limpo', 'sentimento_value']].sample(5)

DataFrame limpo após limpeza e mapeamento:

                                           texto_limpo  sentimento_value
122  estou muito arrependido com esta compra dinhei...                 0
193  pessima experiencia o cadeira gamer quebrou no...                 0
200  estou muito frustrado com esta compra dinheiro...                 0
331  simplesmente perfeito o teclado funciona muito...                 1
444  pessima experiencia o teclado quebrou no prime...                 0